#!/bin/bash

echo "========================================"
echo "多模态检索系统 - 前端已合并"
echo "========================================"
echo ""
echo "注意: 新架构已合并前后端为单一 NiceGUI 应用。"
echo "不再需要单独启动前端。"
echo ""
echo "请使用以下命令启动："
echo "  bash start_all.sh    # 后台启动"
echo "  bash start_poc.sh    # 后台启动（POC 模式）"
echo "  bash start_backend.sh  # 前台启动"
echo ""
echo "访问地址: http://localhost:8080"
echo ""
